--Zombie Survival Tank Boss Class by Mka0207 : http://steamcommunity.com/id/mka0207/
--Tank Model by MrPutisher : http://steamcommunity.com/profiles/76561198028565839

if CLIENT then

	AddCSLuaFile("autorun/sh_loadclasses.lua")
	AddCSLuaFile("zombieclasses/boss_tank.lua")

end

if SERVER then

	include("zombieclasses/boss_tank.lua")
	
	resource.AddFile( "materials/models/enhanced_infected/hulk/hulk_02.vmt" )
	resource.AddFile( "materials/models/enhanced_infected/hulk/hulk_02.vtf" )
	resource.AddFile( "materials/models/enhanced_infected/hulk/hulk_02_normal.vtf" )
	resource.AddFile( "materials/models/enhanced_infected/hulk/hulk_02_underpants.vmt" )
	resource.AddFile( "materials/models/enhanced_infected/hulk/hulk_02_underpants.vtf" )
	resource.AddFile( "materials/models/enhanced_infected/hulk/hulk_02_underpants_n.vtf" )
	resource.AddFile( "materials/models/enhanced_infected/hulk/hulk_02_wrink_norml.vtf" )
	resource.AddFile( "models/enhanced_infected/hulk_2.mdl" )
	resource.AddFile( "models/infected/anim_hulk.mdl" )
	resource.AddFile( "sound/footsteps/tank/walk/tank_walk01.wav" )
	resource.AddFile( "sound/footsteps/tank/walk/tank_walk02.wav" )
	resource.AddFile( "sound/footsteps/tank/walk/tank_walk03.wav" )
	resource.AddFile( "sound/footsteps/tank/walk/tank_walk04.wav" )
	resource.AddFile( "sound/footsteps/tank/walk/tank_walk05.wav" )
	resource.AddFile( "sound/footsteps/tank/walk/tank_walk06.wav" )
	resource.AddFile( "sound/tank/voice/attack/tank_attack_01.wav" )
	resource.AddFile( "sound/tank/voice/attack/tank_attack_02.wav" )
	resource.AddFile( "sound/tank/voice/attack/tank_attack_03.wav" )
	resource.AddFile( "sound/tank/voice/attack/tank_attack_04.wav" )
	resource.AddFile( "sound/tank/voice/attack/tank_attack_05.wav" )
	resource.AddFile( "sound/tank/voice/attack/tank_attack_06.wav" )
	resource.AddFile( "sound/tank/voice/attack/tank_attack_07.wav" )
	resource.AddFile( "sound/tank/voice/attack/tank_attack_08.wav" )
	resource.AddFile( "sound/tank/voice/attack/tank_attack_09.wav" )
	resource.AddFile( "sound/tank/voice/die/tank_death_01.wav" )
	resource.AddFile( "sound/tank/voice/die/tank_death_02.wav" )
	resource.AddFile( "sound/tank/voice/die/tank_death_03.wav" )
	resource.AddFile( "sound/tank/voice/die/tank_death_04.wav" )
	resource.AddFile( "sound/tank/voice/die/tank_death_05.wav" )
	resource.AddFile( "sound/tank/voice/die/tank_death_06.wav" )
	resource.AddFile( "sound/tank/voice/die/tank_death_07.wav" )
	resource.AddFile( "sound/tank/voice/idle/tank_voice_01.wav" )
	resource.AddFile( "sound/tank/voice/idle/tank_voice_02.wav" )
	resource.AddFile( "sound/tank/voice/idle/tank_voice_03.wav" )
	resource.AddFile( "sound/tank/voice/idle/tank_voice_04.wav" )
	resource.AddFile( "sound/tank/voice/idle/tank_voice_05.wav" )
	resource.AddFile( "sound/tank/voice/idle/tank_voice_06.wav" )
	resource.AddFile( "sound/tank/voice/idle/tank_voice_07.wav" )
	resource.AddFile( "sound/tank/voice/idle/tank_voice_08.wav" )
	resource.AddFile( "sound/tank/voice/idle/tank_voice_09.wav" )
	resource.AddFile( "sound/tank/voice/pain/tank_pain_01.wav" )
	resource.AddFile( "sound/tank/voice/pain/tank_pain_02.wav" )
	resource.AddFile( "sound/tank/voice/pain/tank_pain_03.wav" )
	resource.AddFile( "sound/tank/voice/pain/tank_pain_04.wav" )
	resource.AddFile( "sound/tank/voice/pain/tank_pain_05.wav" )
	resource.AddFile( "sound/tank/voice/pain/tank_pain_06.wav" )
	resource.AddFile( "sound/tank/voice/pain/tank_pain_07.wav" )
	resource.AddFile( "sound/tank/voice/pain/tank_pain_08.wav" )
	resource.AddFile( "sound/tank/voice/pain/tank_pain_09.wav" )
	resource.AddFile( "sound/tank/voice/yell/tank_yell_01.wav" )
	resource.AddFile( "sound/tank/voice/yell/tank_yell_02.wav" )
	resource.AddFile( "sound/tank/voice/yell/tank_yell_03.wav" )
	resource.AddFile( "sound/tank/voice/yell/tank_yell_04.wav" )
	resource.AddFile( "sound/tank/voice/yell/tank_yell_05.wav" )
	resource.AddFile( "sound/tank/voice/yell/tank_yell_06.wav" )
	resource.AddFile( "sound/tank/voice/yell/tank_yell_07.wav" )
	resource.AddFile( "sound/tank/voice/yell/tank_yell_08.wav" )
	resource.AddFile( "sound/tank/voice/yell/tank_yell_09.wav" )
	resource.AddFile( "sound/zombiesurvival/tank_theme.mp3" )

end